name: ubuntu

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-24.04 ]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'pip' # caching pip dependencies          

      - name: Install Packages
        run: |
          echo ${{ github.server_url }}
          sudo apt-get -o DPkg::Lock::Timeout=1200 -y update
          sudo apt-get -o DPkg::Lock::Timeout=1200 -y install ninja-build \
          libdrm-dev libinput-dev libsystemd-dev libxkbcommon-dev hwdata \
          mesa-common-dev libegl1-mesa-dev libgles2-mesa-dev mesa-utils libgbm-dev libvulkan-dev
          
          pip install --user meson
          meson --version
          gcc --version

      - name: Configure Meson
        run: |
          cd ${{github.workspace}}
          meson setup buildDir --default-library static

      - name: Build
        # Build your program with the given configuration
        run: ninja -C ${{github.workspace}}/buildDir
